In [6]:
import pandas as pd
pd.set_option('display.max_rows', None, 'display.max_columns', None)

In [7]:
df = pd.read_csv('creditcard.csv')

In [8]:
df.shape

(284807, 31)

In [9]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [10]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [11]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import KFold, GridSearchCV
import numpy as np

In [16]:
log_class = LogisticRegression()

In [17]:
grid = {
    'C': 10.0**np.arange(-2,3), ## 10 raised to -2 till 10 raised to 3
    'penalty': ['l1', 'l2']
}

In [18]:
cv = KFold(n_splits=5, shuffle= False, random_state=False)

E:\installations\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.7)

In [21]:
clf = GridSearchCV(estimator=log_class, param_grid=grid,cv=cv, scoring='f1_macro', n_jobs=-1)

In [22]:
clf.fit(X_train, y_train)

E:\installations\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=False, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [23]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('##################')
print(classification_report(y_test, y_pred))

[[85271    40]
 [   53    79]]
##################
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85311
           1       0.66      0.60      0.63       132

    accuracy                           1.00     85443
   macro avg       0.83      0.80      0.81     85443
weighted avg       1.00      1.00      1.00     85443



In [24]:
print(accuracy_score(y_test, y_pred))

0.9989115550718023


In [25]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
class_weight = dict({0:1, 1:100})

In [30]:
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [31]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('##################')
print(classification_report(y_test, y_pred))
print('################')

[[85309     2]
 [   29   103]]
##################
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85311
           1       0.98      0.78      0.87       132

    accuracy                           1.00     85443
   macro avg       0.99      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443

################


In [32]:
print(accuracy_score(y_test, y_pred))

0.9996371850239341


In [33]:
# Under sampling

In [34]:
from imblearn.under_sampling import NearMiss

In [37]:
from collections import Counter

In [39]:
ns = NearMiss(0.8)
X_train_ns, y_train_ns = ns.fit_sample(X_train, y_train)

In [40]:
print(" The number of classes before fit {}".format(Counter(y_train)))
print(" The number of classes after fit {}".format(Counter(y_train_ns)))

 The number of classes before fit Counter({0: 199004, 1: 360})
 The number of classes after fit Counter({0: 450, 1: 360})


In [41]:
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [42]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('##################')
print(classification_report(y_test, y_pred))
print('################')

[[62999 22312]
 [   11   121]]
##################
              precision    recall  f1-score   support

           0       1.00      0.74      0.85     85311
           1       0.01      0.92      0.01       132

    accuracy                           0.74     85443
   macro avg       0.50      0.83      0.43     85443
weighted avg       1.00      0.74      0.85     85443

################


In [43]:
print(accuracy_score(y_test, y_pred))

0.7387381061058249


In [44]:
### Over sampling

In [45]:
from imblearn.over_sampling import RandomOverSampler

In [48]:
os = RandomOverSampler(0.5)
X_train_ns, y_train_ns = os.fit_sample(X_train, y_train)

E:\installations\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [49]:
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [50]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('##################')
print(classification_report(y_test, y_pred))
print('################')

[[85307     4]
 [   26   106]]
##################
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85311
           1       0.96      0.80      0.88       132

    accuracy                           1.00     85443
   macro avg       0.98      0.90      0.94     85443
weighted avg       1.00      1.00      1.00     85443

################


In [51]:
print(accuracy_score(y_test, y_pred))

0.9996488887328394


In [52]:
from imblearn.combine import SMOTETomek

In [53]:
os = SMOTETomek(0.5)
X_train_ns, y_train_ns = os.fit_sample(X_train, y_train)

print(" The number of classes before fit {}".format(Counter(y_train)))
print(" The number of classes after fit {}".format(Counter(y_train_ns)))

E:\installations\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


 The number of classes before fit Counter({0: 199004, 1: 360})
 The number of classes after fit Counter({0: 198187, 1: 98685})


In [54]:
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [55]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('##################')
print(classification_report(y_test, y_pred))
print('################')
print(accuracy_score(y_test, y_pred))

[[85300    11]
 [   21   111]]
##################
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85311
           1       0.91      0.84      0.87       132

    accuracy                           1.00     85443
   macro avg       0.95      0.92      0.94     85443
weighted avg       1.00      1.00      1.00     85443

################
0.9996254813150287


In [56]:
# Ensemble techniques

In [57]:
from imblearn.ensemble import EasyEnsembleClassifier

In [58]:
easy = EasyEnsembleClassifier()
easy.fit(X_train,y_train)


EasyEnsembleClassifier()

In [59]:
y_pred = easy.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('##################')
print(classification_report(y_test, y_pred))
print('################')

[[81880  3431]
 [   10   122]]
##################
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85311
           1       0.03      0.92      0.07       132

    accuracy                           0.96     85443
   macro avg       0.52      0.94      0.52     85443
weighted avg       1.00      0.96      0.98     85443

################
